### ISSUE TITLE
Is it ready?

### ISSUE THREAD

**Issue by xgrommx** [SodiumFRP/sodium-typescript#1]

**Comment by the-real-blackh** [comment]
No, not ready yet. I will get some time this weekend.

**Comment by xgrommx** [comment]
@the-real-blackh how about your book? maybe exists some coupon, because for me now it too expensive. I wanna to buy it!

**Comment by the-real-blackh** [comment]
Every month or so they send me a 50% discount coupon. I'll post it here when it comes.

**Comment by clinuxrulz** [comment]
Are the operational semantics the same as the Java version?, Just with the added manual resource management for streams/events cells/behaviours which I assume to be Source/Vertex.

**Comment by the-real-blackh** [comment]
Yes, the semantics will be identical, just API differences to make it more idiomatic Typescript/Javascript.

**Comment by the-real-blackh** [comment]
Hey xgrommx,

Deal of the Day June 14: Half off my book Functional Reactive Programming. Use code dotd061416au at http://bit.ly/1UsAEUH

Links should be directed to the DOTD's page at https://www.manning.com/dotd.

**Comment by the-real-blackh** [comment]
The typescript version of Sodium is substantially complete. Switch is not done yet, and neither is continuous time. You're welcome to start testing.

**Comment by the-real-blackh** [comment]
Deal of the Day July 5: Half off my book Functional Reactive Programming. Use code dotd070516au at http://bit.ly/29bjZUZ

**Comment by xgrommx** [comment]
@the-real-blackh But do you will to continue to provide coupons here if they will be available?

**Comment by the-real-blackh** [comment]
I am very happy to announce that the Typescript implementation of Sodium is ready!

It can now CLEAN UP CYCLES in the listeners it uses internally! It will need more testing, but it seems we now have an implementation of FRP for Javascript with full, correct and automatic memory management.

This method of memory management will also work for the C++ implementation, which currently has problems in this area. The causes are different, but the same solution will work for Javascript and C++.

**Comment by the-real-blackh** [comment]
Another one:

Deal of the Day July 15: Half off my book Functional Reactive Programming. Use code dotd071516au at http://bit.ly/29ES8Oc 

From now on I'll post them here: http://sodium.nz/t/frp-book-coupons/48
