### ISSUE TITLE
Replicating example from the book

### ISSUE THREAD

**Issue by graforlock** [SodiumFRP/sodium-typescript#13]
Trying to replicate the book example from Java, porting to a typescript version.

Here's the code form main.ts:

``` typescript
import Button from './button';
import SLabel from './slabel';
import { CellLoop, Stream, transactionally } from 'sodiumjs';

class FRP
{
    public static main()
    {
        transactionally(() =>
        {
            const value: CellLoop<number> = new CellLoop<number>();
            const label: SLabel = new SLabel(value.map(i => i.toString()));

            const btnPlus: Button = new Button("+");
            const btnMinus: Button = new Button("-");

            const sDelta: Stream<number> = btnPlus.sClicked.map(u => 1)
                .orElse(btnMinus.sClicked.map(u => -1));

            const sUpdate: Stream<number> = sDelta.snapshot(value, (delta, _value) =>
            {
                return delta + _value;
            }).filter(n => n >= 0);

            value.loop(sUpdate.hold(0));

        });
    }
}

FRP.main();
```

and slabel.ts:

``` typescript
import {Cell, Operational} from 'sodiumjs';

class SLabel
{
    private label: HTMLElement;
    private l: any;

    constructor(text: Cell<string>)
    {
        this.l = Operational.updates(text).listen(t =>
        {
            this.setText(t);
        });

        this.label = document.createElement('h5');
        this.render();

    }

    setText(t: string)
    {
        this.label.textContent = t;
    }

    render()
    {
        document.body.appendChild(this.label);
    }
}

export default SLabel;
```

and button.ts (for completeness sake):

``` typescript
import {Unit, Stream, StreamSink} from 'sodiumjs';

class Button
{
    private button: HTMLElement;
    private sClickedSink: StreamSink<Unit>;

    public sClicked: Stream<Unit>;

    constructor(name: string)
    {
        this.button = document.createElement('button');
        this.button.textContent = name;
        this.sClickedSink = new StreamSink<Unit>();
        this.sClicked = this.sClickedSink;

        this.button.addEventListener('click', (event: Event) =>
        {
            this.sClickedSink.send(Unit.UNIT);
        });

        this.render();
    }

    render(): Button
    {
        document.body.appendChild(this.button);
        return this;
    }
}

export default Button;
```

The problem with this is that it never registers initial value 0 from the first `value.loop(sUpdate.hold(0))`, so no label field value is passed in at the beginning of the transaction, resulting in no textContent.

What is the solution for the typescript version?

**Comment by Ziriax** [comment]
I think `Operational.updates` only fires the changes to the cell, not the initial value? If I look at the typescript code, the function just returns `c.getStream__();`

**Comment by Ziriax** [comment]
If you look at the C# source code of SLabel, it also samples the initial cell value:

```
        public SLabel(Cell<string> text)
        {
            Action<string> setText = t => this.Dispatcher.InvokeIfNecessary(() => this.Text = t);

            // Set the initial value at the end of the transaction so it works with CellLoops.
            Transaction.Post(() => setText(text.Sample()));

            // ReSharper disable once UseObjectOrCollectionInitializer
            List<IListener> listeners = new List<IListener>();
            listeners.Add(Operational.Updates(text).Listen(setText));

            this.listeners = listeners;
        }

```

Maybe it would be handy to have an operational method that also first the initial cell's value, i.e. `Operational.Values`? But that might break the semantics, I'm not sure.

**Comment by graforlock** [comment]
If you mean sample the initial value sample via:
 
```java 
Transaction.post(text.sample())
``` 
Then the typescript version doesn't have ```Transaction``` export module, only ```transactionally``` function.

**Comment by Ziriax** [comment]
I have no experience with the TS version, but indeed, that seems to be missing. But it does expose the `currentTransaction`:

`export let currentTransaction : Transaction = null;`

and also the `post` method on the `Transaction` seems public.

So you could cook it yourself, something like

```
function asap(action: () => void, priority=0) {
     if (currentTransaction) {
        currentTransaction.post(priority, action);
     } else {
        action();
     }
}
```

where `asap` is possibly the worst name I could use ;-)

**Comment by graforlock** [comment]
Yes, It does in fact expose ```currentTransaction``` in the ```./src``` typescript file, but the default js ```./dist```, which is the entry point,  does not have that export capability. As per:

https://github.com/SodiumFRP/sodium-typescript/blob/master/dist/lib/Sodium.js

it kind of only exports transactionally.

**Comment by Ziriax** [comment]
Indeed.

**Comment by the-real-blackh** [comment]
First, @graforlock - thanks for doing this. Can we check it in when you've got it going?

We need to make 'post' public. Anyone care to submit a patch?

**Comment by graforlock** [comment]
@the-real-blackh - Sure, I will, once I fiddle with it enough and yield some result.

**Comment by graforlock** [comment]
Exporting just currentTransactions didn't quite work, as suggested earlier by @Ziriax.

However, it works. But, when the whole Transaction is exported in ```./dist/lib/Sodium.js:
```typescript
exports.Transaction = Transaction_1;
```
Export added to ```./dist/lib/Sodium.d.ts``` type definition: 
```typescript
export { transactionally, Transaction } from "./Transaction";
```
And so posting would look like:
```typescript
        Transaction.currentTransaction.post(0, () =>
        {
            this.setText(text.sample());
        });
```
Not too elegant I presume, but samples the initial value for 0.

**Comment by Ziriax** [comment]
note that currentTransaction can be null.

Also, Typescript 2.0 is out. This sounds like a good fit for Sodium, it tracks nullables now, and many more goodies.

**Comment by graforlock** [comment]
It should be null whenever there is no transaction available. The problem is that then ```currentTransaction``` export is always null, meaning that it loses module context of references. 

Instead, the whole module could be exported, then it would just be:
```typescript
import { /* other imports ,*/ Transaction } from 'sodiumjs';

// ...later in the code

Transaction.transactionally(()=>{
// ...some code...
})
```

```typescript 
// ...somewhere in the class
Transaction.currentTransaction.post(priority, () => {
// ...some code...
})
```
So, modules would only have to expose, as per ```d.ts``` : 

```typescript
export { transactionally, Transaction } from "./Transaction";
````

**Comment by Ziriax** [comment]
IMHO the Typescript API should be as close as possible to the other APIs, e.g. the C# code for the public Transaction.Post is:

```
        /// <summary>
        ///     Execute an action after the current transaction is closed
        ///     or immediately if there is no current transaction.
        /// </summary>
        /// <param name="action">
        ///     The action to run after the current transaction is closed
        ///     or immediately if there is no current transaction.
        /// </param>
        public static void Post(Action action)
        {
            // -1 will mean it runs before anything split/deferred, and will run
            // outside a transaction context.
            Run(trans => trans.Post(-1, _ => action()));
        }
```

So Post can be called even if no transaction exists.

**Comment by graforlock** [comment]
Yes, indeed. I am probably more C# proficient than typescript to make it click (along with the build).

**Comment by the-real-blackh** [comment]
Instead of transactionally we could have Transaction.run() - that would make it more like C# and Java. Because of discussions on another thread, in all versions we also need to add Transaction.isActive() which tells you whether a transaction is active on the current thread (in Javascript only the current thread exists):

Transaction.run(action)
Transaction.post(action)
Transaction.isActive() - returns boolean

Does that look reasonable?

**Comment by Ziriax** [comment]
Sounds good to me. I still don't know though if isActive is valid when using Sodium from multiple threads.

**Comment by the-real-blackh** [comment]
Transaction.isActive() would return true *only* if there is a transaction open on the current thread.

**Comment by graforlock** [comment]
I think we can close this issue for now as its been pretty much (more or less) sorted.
