### ISSUE TITLE
automate publishing of package updates to npm registry/bower & others

### ISSUE THREAD

**Issue by rixrix** [SodiumFRP/sodium-typescript#19]
hook up TravisCI on publishing package update to npm or bower registry. There's a big community of NuGet users particularly those who are using Visual Studio so it'd be good sync to this registry as well. There was a discussion of delayed publishing to npm due to non-organization account, see #16 

refs
* https://docs.travis-ci.com/user/deployment/npm/

**Comment by rixrix** [comment]
@graforlock @the-real-blackh I didn't know that we can have multiple admin/maintainer to a published npm package - I think it's possible. If you could drop your username here and I'll try to add you as owner. thank you - I guess no need for an org account, previously mentioned. thanks

**Comment by graforlock** [comment]
my username is, i believe, the same on npm **graforlock**

**Comment by rixrix** [comment]
thanks, added you to npm maintainer.

**Comment by graforlock** [comment]
Have you made some steps to implement it @rixrix  yet ?  I'm pretty busy lately, but need to find some time to do a thing or two on the weekend.

**Comment by rixrix** [comment]
@graforlock I'm assigning to this to you, thanks

**Comment by graforlock** [comment]
That hangs around and I have atm zero time to fix it due to me working on my start-up. Would anyone commit to it?

**Comment by rixrix** [comment]
adding this to my todo, I have a few repos that needs to be in TravisCI.

**Comment by rixrix** [comment]
@graforlock @the-real-blackh this in currently in progress, FYI - so I might do a few releases for testing purposes.

**Comment by rixrix** [comment]
I managed to get this working today, note that this is pretty basic and there's plenty of room for improvement especially on the release workflow, see #27 for extra info:

Whats New ?
* anyone with access to pushing git tag can trigger a deployment to npm registry
* how to bump package.json version and create npm version tag ?

Just follow or run npm script [1], or try do any of the following release scenario:

* Major: `npm version major`:
* Minor: `npm version minor`:
* Patch: `npm version patch`

On every `version` command, it will execute the scripts in package.json file
* `preversion`: runs our test suite
* `postversion`: updates the package.json version, creates a git tag, and push the new tag to origin
* Once tag is in git repo, TravisCI will trigger a build and do a npm release

@graforlock @the-real-blackh if you have, let me know if you're happy with this and we can close this task. I might file a couple of tasks for build improvement, best time to invite community contributors ;)

[1] https://docs.npmjs.com/cli/version

**Comment by rixrix** [comment]
closing this off. I'll update the readme. thanks
