### ISSUE TITLE
packaging uncompiled TypeScript as npm and bower module

### ISSUE THREAD

**Issue by rixrix** [SodiumFRP/sodium-typescript#2]
Hi,

There has been a lot of activities with this repo, maybe it's time to make an initial progress in publishing the uncompiled TS as NPM and bower module ?

If there are no takers then I'm keen on doing this. Let me know. Thanks

**Comment by the-real-blackh** [comment]
I'd be most grateful if you would do that. It would save me a lot of time because I have no idea how to do it. The API isn't quite finished yet, so say it's pre-alpha and give it a version number like 0.0.1.
Or hold off until everything's working, which should be within a week or so.

I intend to write some kind of fairly complex demo once I've finished it.

**Comment by rixrix** [comment]
@the-real-blackh sounds good to me, we can always flag the work as work-in-progress. We'll push it once ready for public use. thanks

**Comment by the-real-blackh** [comment]
Hi @rixrix! Now that the typescript implementation is ready, I would be most grateful if you can help with getting it packaged up. Sadly, I am a Javascript ignoramus and have no idea how to do this. It would also be great if we can make a Javascript-only version. Thank you very much for offering to help with this.
Currently it's alpha quality so we could give it a version number like 0.9.0. I'll leave that up to your imagination. I'll do a demo or two just to take it for a test.

**Comment by rixrix** [comment]
@the-real-blackh I saw the announcement, you've done an awesome work. The packaged version would definitely end up as JS-only with an included type definition (`xxx.d.ts`) for TypeScript users. 

> Sadly, I am a Javascript ignoramus 

I'm still scratching the surface as well ;) , we might get some expert advise at some stage. 

Anyway, I'll work it out and see if I can submit a pull request soon. Thanks

**Comment by the-real-blackh** [comment]
@rixrix You should have write access now. Tell me if I didn't do it right. Thank you!

**Comment by rixrix** [comment]
@the-real-blackh got the write access, thanks

**Comment by rixrix** [comment]
closing this off, sodium is now available in npm and bower
