### ISSUE TITLE
typescript-collections vs. immutable.js

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#21]
Is there a difference between them - could the dependency be swapped out to immutable.js with little to no pain?

**Comment by the-real-blackh** [comment]
typescript-collections provides mutable data structures. In the internal implementation of Sodium we don't need to use immutable data structures, but we could. The mutable ones are probably more efficient, but they do add to the size of the download. If the user is going to use an immutable library anyway, then that might be a good reason to use it.
So there are a few things to weigh up, but the amount of work to change over would not be that great.

**Comment by graforlock** [comment]
bucklescript (ocaml to js) compiler uses Immutable with success. From experience, its painful to use immutable.js, as features are not yet there as they would work in a full featured functional language. There are some cases (for example, isomorphic apps) where they are being parsed into regular objects from records and maps. That makes them painful to re-assemble back to these with nothing helping out with this particular issue.
