### ISSUE TITLE
Required listener for snapshot/loop?

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#22]
Not sure if this is by design... the following code results in errors when sUpdate.listen() is commented out:

```
Transaction.run((): void => {
    let stream = new StreamSink<number>();

    //see https://github.com/SodiumFRP/sodium-typescript/blob/master/src/lib/TimerSystem.ts#L45

    stream.listen(n => {});

    let totalTime = new CellLoop<number>();
    let sUpdate = stream.snapshot(totalTime, (a,b) => a+b);

    totalTime.loop(sUpdate.hold(0));

    //removing this breaks things, even if the above listener is kept
    sUpdate.listen(n => {});

    setInterval(() => stream.send(1), 100);
});
```

In this specific example the errors are about calling send() more than once in the console - though in a different test I believe it was about sending() before attaching a listener (even when explicitly attaching one to the stream, like the first listen() in the example here)

Is this by design?

**Comment by graforlock** [comment]
You are essentially then having a brand new stream delta to which there is no listener attached even though transaction is initialised. Is that not the problem?

**Comment by dakom** [comment]
Can you explain a little more the role of sUpdate.listen() there? e.g. in my newbie understanding, which is probably wrong, I'd think it's like this (same code just adding comments):

> Transaction.run((): void => {
>     //create a stream sink that will be used to generate a sequence
>     let stream = new StreamSink<number>(); 
> 
>     //evidently send() requires that there always be a listener first
>     //see https://github.com/SodiumFRP/sodium-typescript/blob/master/src/lib/TimerSystem.ts#L45
>     stream.listen(n => {});
>
>     //create a cell to hold the total time
>     let totalTime = new CellLoop<number>();
>
>     //get the value of totalTime, modify it, and return a stream with the new value
>     let sUpdate = stream.snapshot(totalTime, (a,b) => a+b);
> 
>     //set totalTime's stream to sUpdate (requires loop since sUpdate depends on totalTime)
>     totalTime.loop(sUpdate.hold(0));
> 
>     //removing this breaks things, even if the above listener is kept
>     //not quite sure why? what does this affect?
>     sUpdate.listen(n => {});
> 
>    //generate a sequence and send it to the stream
>     setInterval(() => stream.send(1), 100);
> });

**Comment by graforlock** [comment]
sUpdate.snapshot basically returns a new `StreamWithSend` that you then loop, and that new stream has no listeners.

So you probably get (at first):

`"Error: send() was invoked before listeners were registered`

**Comment by dakom** [comment]
And that's a fundamental thing? `StreamWithSend` require listeners in order to send? (I can understand this from like a plumbing perspective, just making sure)

Thanks!

**Comment by graforlock** [comment]
In order to be registered in transaction, I assume yes. Otherwise, if nothing registers and calls/yields the stream for its side effects you may as well remove all of the code whatsoever as its pretty redundant.

**Comment by dakom** [comment]
Thanks! Closing this as an "issue" but happy to learn more :)

**Comment by the-real-blackh** [comment]
The reason why listeners have to be registered before you can send something is to do with the tricky way in which the memory is managed in the typescript implementation. It's observer pattern under the covers. In other implementations we use finalizers to clean up unused listeners. In Javascript there are no finalizers, so we can't do this. Instead we track it through listeners. So the listeners have to be in place before anything can work.
