### ISSUE TITLE
unlisten is not a function

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#25]
The [comments  for Cell.ts](https://github.com/SodiumFRP/sodium-typescript/blob/master/src/lib/Cell.ts#L353) say that Cell.listen() returns a Listener that can be removed via unlisten().

However, when I try it in the code below I have two problems:

1. Listen is not an available module (so I cast to `any`)
2. listener.unlisten() doesn't exist

Am I missing something? Is there a better way to delete a cell? (I assumed if I 'unlisten()' its listener and it goes out of scope - it's garbage collected... but maybe that's the wrong assumption?)

(_note - it doesn't actually go out of scope here... this is just to demo the unlisten() issue. The book mentioned a cell switching itself out of existence - can someone supply an example of that based on the below, where `holder` completely goes away?_)

```
Transaction.run((): void => {
    let counter = new StreamSink<number>();
    let holder = counter.hold(Date.now());
    let listener:any = holder.listen(console.log);
    
    //how to destroy holder?
    //this says unlisten is not a function
    listener.unlisten();
    
    setInterval(() => counter.send(Date.now()), 300);
});
```

**Comment by dakom** [comment]
In fact - searching for unlisten() in this repo yields only that comment on the Cell.ts source o_O

**Comment by the-real-blackh** [comment]
David,

The value returned by listen() is a function. So it should look like this:

    const unlisten = holder.listen(console.log);
    ...

    unlisten();


Steve

**Comment by dakom** [comment]
Perfect, thanks!
