### ISSUE TITLE
Integration with TravisCI

### ISSUE THREAD

**Issue by rixrix** [SodiumFRP/sodium-typescript#3]
this will probably come at some stage and having CI kick in to run all the tests, or deployment would be great.

https://travis-ci.org/

**Comment by rixrix** [comment]
@the-real-blackh I might admin access to this repo so I can hook up https://travis-ci.org/ ? thanks

**Comment by the-real-blackh** [comment]
You should have admin privilege now. Let me know if you have any trouble with it. 
On 27/07/2016 2:29 am, Richard Sentino <notifications@github.com> wrote:@the-real-blackh I might admin access to this repo so I can hook up https://travis-ci.org/ ? thanks
