### ISSUE TITLE
examples and test

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#32]
It's not 100% clear to me what these folders are for:

1. [src/test](https://github.com/SodiumFRP/sodium-typescript/tree/master/src/test)
2. [examples/basic](https://github.com/SodiumFRP/sodium-typescript/tree/master/examples/basic)

They seem related as though `examples/basic` is built from `src/test` and are essentially unit tests... if that's right, maybe they should be moved alongside the other tests in [spec/](https://github.com/SodiumFRP/sodium-typescript/tree/master/spec) ?

While not a huge deal, it's a bit confusing to see the different test folders and be unable to run one of them (I didn't see anything in `package.json` that runs this build)

**Comment by dakom** [comment]
Assuming by the thumbs up I can go ahead and do a little housecleaning ;)

**Comment by dakom** [comment]
egh.... nevermind, karma/webpack are super annoying and it doesn't feel like a good use of energy tweaking it within the current constraints.

@graforlock mentioned fuse-box... I haven't used that but it looks great!

Alternatively, I have a barebones setup at https://github.com/dakom/html5-boilerplate/tree/barebones that I could use if we don't mind changing the structure here a bit.

Either way would be a nicer dev experience imho.

**Comment by the-real-blackh** [comment]
Yes, house clean if you feel inspired. You can't make an omelette without breaking a few eggs.

**Comment by dakom** [comment]
OK, I've now migrated the project totally over to fuse-box... there's some additional commands that make development easier. Updated all in the Readme :)
