### ISSUE TITLE
Fork vs. local branch

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#35]
Thanks for inviting me to the team @the-real-blackh ! 

For pushing new features, should I just work on a local branch and make PR requests from there? (i.e. then I can delete my fork)

Specifically for improving fantasy-land compatibility/tests and making contributions to #32 - should I just merge into master as long as all tests pass? (it won't be touching any of the real internals of sodium, just aliases and the testing framework at this point)

**Comment by the-real-blackh** [comment]
Welcome and thank you for your wonderful contributions!

Yes, please check your fantasy-land stuff into master. Use branches wherever you think it's appropriate.
