### ISSUE TITLE
Deployed dist folder

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#36]
I just released the new fuse-box powered build (thanks for the suggestion @graforlock !)

Couple followup questions:

1. npm and browser loading work, but I'm unfamiliar with bower/yarn - should those automatically work if npm does?

2. it would be nice if we could .gitignore the `dist` folder in the master and simply have Travis build and deploy without it. From some googling it seems like the reason it's there is maybe having to do with bower. Can someone confirm or maybe suggest a strategy so we can keep the `dist` folder out of `master` yet still hit the deployment targets?

**Comment by clinuxrulz** [comment]
For bower you still need to register your project. Its a first come first serve for project name:
See: https://bower.io/docs/creating-packages/
Yarn I'm unfamiliar with, and not sure about #2.

**Comment by clinuxrulz** [comment]
I'm wrong again.
Post install script support in bower: https://github.com/bower/spec/blob/master/config.md#scripts

**Comment by clinuxrulz** [comment]
I might be wrong about the post install script
https://github.com/bower/spec/blob/master/config.md#scripts

**Comment by dakom** [comment]
Thanks for the insight! It seems the bower deploy worked, and since the CDN link is pulling from the dist folder too it makes sense to just leave it in.  Closing the issue for now :)

**Comment by dakom** [comment]
I'm re-opening this for consensus... checking in the `dist` folder just feels wrong... can someone give me a thumbs up to .gitignore it? I'll go ahead and do that once there's at least a single thumb-up ;)

If that breaks anyone's actual use, I believe we will then hear about it and can fix without needing to check that folder in.

**Comment by dakom** [comment]
Seems like Bower itself is recommending a migration to yarn/npm... surely the approach of hosting build artifacts is no longer necessary for modern js/ts development. Going to .gitignore it
