### ISSUE TITLE
Fantasy-land compatibility for Stream

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#39]
It seems Cell is working well but there's still an unsolved question about `concat()` for Stream.

Picking up from the closed ticket at https://github.com/SodiumFRP/sodium-typescript/issues/30 -especially @the-real-blackh 's point that "if the other value is also a monoid, then you would use that as the merge argument"
...

Given:
```
a = Stream([3]);
b = Stream([4]);
const c = concat(a, b);
```

Which of the following should `c` be?

1. `Stream([3])`
2. `Stream([3,4])`

Currently it's the former due to `concat` not checking if the underlying value is also a Monoid, but perhaps it should be the latter? Here is as fiddle to show it in action right now - https://jsfiddle.net/dakom/ud7wq8f9/

If it should be the latter, then should `a.send([6])` result in `c` being `Stream([6,4])` ?

Thanks to James Forbes for bringing this to my attention!

**Comment by clinuxrulz** [comment]
Both 1 & 2 are valid. It just depending on the end-users intention. The general pattern used in Haskell is to make use of wrapper types so the end-user can pick the implementation they expect.
E.g.: A Set can have Monoid implementations for Union (OR), Intersection (AND), Disjoint Union (XOR), and all are valid.
I'm unfamiliar with fantasy-land. But if it auto-selects the type class implementation based on its parameter types (like haskell, instead of passing around the type class implementation). Then I think you will need to resort to wrapper types as well in order the select the correct implementation.

**Comment by dakom** [comment]
Thanks @clinuxrulz

Can you share a little more info or maybe a small example of how the users intention could be detected in Typescript? I apologize but I'm just not seeing it yet - maybe I need to start learning Haskell/Purescript ;) , or maybe it's a limitation of Typescript itself? 

As of right now it only does an `orElse` with the other stream (hence why the result in the example was simply `Stream([3])`, i.e.

```
//concat :: Semigroup a => a ~> a -> a
'fantasy-land/concat'(a:Stream<A>) : Stream<A> {
  return this.orElse(a);
}
```

**Comment by clinuxrulz** [comment]
After looking at fantasy-land, you are unable to do "value-level typeclasses", it is a limitation of fantasy-land, not a limitation of javascript. So your left with wrapper types, which is a little bit painful.

By wrapper type, I mean you make a class
```
class StreamContainingMonoid<A> {
    stream: Stream<A>;
    constructor(stream: Stream<A>) {
        this.stream = stream;
    }
}
```
Then you define 'fantasy-land/concat' for ```StreamContainingMonoid```. Its painful and might not be worth it.

**Comment by clinuxrulz** [comment]
"1" is more general than "2". So I'd suggest keeping "1" as the default, and just let the end-user define their own concat method with a different name to do number "2".

**Comment by clinuxrulz** [comment]
I can see you went "2" if possible, otherwise fell back to "1". That is fair enough.

**Comment by dakom** [comment]
I just changed Stream such that when there's a merge event, it will concat the inner values as long as they satisfy the FantasyLand Semigroup spec. Otherwise, if there is no merging, it is the original stream value. 

Is this a good compromise? Do you think it should rather continue to concat and keep the second value on subsequent calls?

Some examples of the current implementation follow below. For the sake of brevity each example doesn't include the common setup which is

```
const a = new StreamSink<T>();
const b = new StreamSink<T>();
const c = concat(a,b);
c.listen(val => console.log(val));

a.send(val1);
b.send(val2);

Transaction.run(() => {
  a.send(val1);
  b.send(val2);
});

a.send(val2);

```

Example: Array
* T = Array<number>
* val1 = [1]
* val2 = [2]

Results:
```
[1]
[2]
[1,2]
[1]
```

Example: number
* T = number
* val1 = 1
* val2 = 2

Results:
```
1
2
1
1
```

Example: string
* T = string
* val1 = "a"
* val2 = "b"

Results:
```
"a"
"b"
"ab"
"a"
```

Example: Array<string>
* T = Array<string>
* val1 = ["a"]
* val2 = ["b"]

Results:
```
["a"]
["b"]
["a","b"]
["a"]
```

**Comment by dakom** [comment]
hehe @clinuxrulz you saw it before I could comment ;)

> I can see you went "2" if possible, otherwise fell back to "1". That is fair enough.

Right, though only on merge events... it doesn't continue to propagate/hold each stream permanently. I could imagine that a hold/propagation like that could be a powerful userland meaning of "concat" but it doesn't feel right from the perspective of the difference between Stream/Cell

In general, do you think the current solution is the best one?

**Comment by clinuxrulz** [comment]
yes, the current solution will be fine. Its sort of like overlapping instances extension in Haskell.

**Comment by dakom** [comment]
okay cool, closing this issue for now then. Thanks for taking a look!

**Comment by clinuxrulz** [comment]
Just for reference, this is why 1 is more general. Because 2 has a constraint on ```a```
```
1: instance Semigroup (Stream a)
2: instance Semigroup a => Semigroup (Stream a)
```
