### ISSUE TITLE
WeakSet / WeakMap alternative sodium impl.

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium-typescript#43]
#42 mentioned JavaScript supports WeakMap

Is there good browser support for either WeakSet / WeakMap these days? If so, then it may be possible for a TypeScript implementation that does not require a GC impl in the library.

Each node could have a strong ref back to its dependency and each dependency node use a WeakSet to point forward to what depends on it. The impl won't be exactly the same as the Java version, because we still don't have finalizers. Maybe a push-pull impl would work better, where nodes get marked as dirty at the right time, then at end of transaction the dirty nodes call their update methods to update there own values (in rank order of course)

Just a thought.

**Comment by clinuxrulz** [comment]
A quick search revealed. IE has no support for WeakSet today, and every other browser supports it.
Yet every browser seems to support WeakMap. 
So ```newtype WeakSet a = WeakMap a ()```

**Comment by Ziriax** [comment]
Good idea. WeakMaps were considered initially, but dropped because they don't have finalizers. However, they can indeed be used to break the strong back references, at least as far as I understand the architecture?

**Comment by the-real-blackh** [comment]
We looked into this a little while back and decided that WeakSet / WeakMap gives no actual way to solve the problem.

**Comment by clinuxrulz** [comment]
Yes. And finalizers were required to auto unhook any dependency nodes from a node when it gets garbage collected. However WeakMap automatically removes its Keys for us.

We only want to keep nodes alive that:
1. Are accessible by the end-users code.
Or 2. Are dependences or deep dependences of the ```keepListenerAlive``` list. (When the end-user does a strong listen, keep until they ```unlisten```)

**Comment by clinuxrulz** [comment]
I just realized you can not iterate over a WeakMap or WeakSet. So its a no go.
