### ISSUE TITLE
Publish your library on npm

### ISSUE THREAD

**Issue by xgrommx** [SodiumFRP/sodium-typescript#5]
@the-real-blackh I think will be better to publish your Sodium to npm and make typescript and typescript-collection as dependencies.

**Comment by xgrommx** [comment]
Also will be better to use [`rollup`](https://github.com/rollup/rollup) for building this library for browser.

**Comment by rixrix** [comment]
@xgrommx sodium is now available in npm , it's in beta ATM and one might get a few hiccups along the way. cheers
