### ISSUE TITLE
Multiple Loop fail (send before listener error)

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/sodium-typescript#67]
I added a new test here: https://github.com/SodiumFRP/sodium-typescript/blob/master/src/tests/unit/MultipleLoop.spec.ts

The last one fails with a "can't send() before listen" type of error as well as failing to clean up registrations... 

Maybe it's my mistake? Please let me know... if it is I'll happily remove the test at next opportunity :)

If it shouldn't fail... any idea what's going on? 

I feel like since the Cell is made up from the Stream, a listen on the Cell should cover the Stream - regardless of whether the Stream is sent inside or outside the Transaction...

**Comment by dakom** [comment]
Oh interesting... when it's a single loop only it passes - I added that in just now

So it's specifically when there's multiple loops _and_ the stream is sent outside the transaction...

**Comment by Ziriax** [comment]
Out of curiosity, does it work when you pass a Lambda2 instead of a regular lambda function?

**Comment by dakom** [comment]
Nope, I tried changing it to this and some other combinations, still fails:

```
        c1.loop(
            s.snapshot3(c1, c2, lambda3((n1, n2, n3) => n1 * n2 * n3, [s, c1, c2])).hold(2)
        );

        c2.loop(
            s.snapshot3(c1, c2, lambda3((n1, n2, n3) => n1 * n2 * n3, [s, c1, c2])).hold(2)
        );
```

**Comment by clinuxrulz** [comment]
What happens when ```send``` is executed after the transaction? (in a separate transaction)

**Comment by dakom** [comment]
Still nope :\ I added in the updates with both the lambda wrapper, and calling send in a transaction - and also tried delaying it for good measure.

As a tip to anyone trying the tests - you can run just this test by running "jest MultiLoop" (requires jest to be installed globally I think)

**Comment by clinuxrulz** [comment]
Your original failing test was enough to demonstrate the problem. I was looking at the passing test falsely thinking it was the one fail. It is another real bug you've found.

**Comment by dakom** [comment]
One of these days I'm hoping to get Java setup so I can try to duplicate this and the other failing test there... so curious if it's related to the GC implementation!

**Comment by clinuxrulz** [comment]
I think so. I suspect it is when collecting cycles on unlisten, it does not seem like a safe place to call it. I don't have access to a computer at the moment, but try a manual collect/gc  at the end of the test or even try unlisten triggering GC through a setTimeout.

**Comment by clinuxrulz** [comment]
I believe #61 might be somehow related to this bug.

**Comment by dakom** [comment]
I'll be afk for a day or two - but happy to try it out when I'm back :)

**Comment by clinuxrulz** [comment]
I've been trying out ```sodium-typescript``` on an allocation at work where I have heavy CellLoops of CellLoops. The memory management keep dropping listeners from ```ssMousePressed``` even when I manually added a dummy listener to stop "stream send before listeners" error.

Here is a hack that worked for me:
I first added to "Transaction.ts":
```
  public static post_(action: () => void): void {
    Transaction.run(() => Transaction.currentTransaction.post(0, action));
  }
```

Then in "Vertex.ts":
I changed:
```Vertex.collectCycles();```
to:
```Transaction.post_(() => Transaction.post_(() => Vertex.collectCycles()));```

And the problem went away, everything was working. It does not solve any extra test cases for sodium though.

**Comment by clinuxrulz** [comment]
Actually the "PASS  src/tests/unit/MultipleLoop.spec.ts" passes.
Only 1 test failing. "FAIL  src/tests/unit/InnerLoop.spec.ts", which was failing beforehand anyway.

**Comment by clinuxrulz** [comment]
@dakom I've modified one of your tests in my fork in a way I believe captures the original intent of the code.

https://github.com/clinuxrulz/sodium-typescript/blob/master/src/tests/unit/InnerLoop.spec.ts

All tests now pass on my fork. If the changes are OK, then the same can be done in this repo.

**Comment by clinuxrulz** [comment]
@dakom
I have not tried any heavy code with the Rust version yet. I'm rather fond of the ease of debugging typescript. I need rust sourcemaps in wasm before I get more deeply involved.

**Comment by dakom** [comment]
Cool :)

Btw - for a bit of irony, now my laptop crashed... in the process of setting up a new one..

Haven't looked at the differences in the code, but if there's no difference in the results it sounds promising!

By difference in results I mean like if the tests as they were also were failing and now pass.

Totally agree that they were a little "throw it all against the wall and see what sticks" and could've used some cleanup ;)

**Comment by clinuxrulz** [comment]
InnerLoop touched the same issue as passing sodium objects through sinks. (Which is not supported). That was when we invented that switch-map and lift tricks. I refactored the test slightly so no dirty tricks are involved and seems to achieve same intent.

**Comment by clinuxrulz** [comment]
As for Vertex.collectCycles(). I had call that in the same place in the Rust version, and when I did I'd get segmentation faults. I had to go to great lengths (even modifying the gc algorithm) to stop theses seg faults. It made me think that decrement is an unsafe place to call collectCycles(). In javascript you won't get a seg fault to let you know something is wrong. So I placed it in a Transaction.post() inside decrement, and it seems to have done the trick.

**Comment by clinuxrulz** [comment]
Unfortunately after putting collectCycles() inside transaction post (after further testing). Some problems of disappearing listeners remained. I'm just calling collectCycles() manually on my end for now (at root level of the source). Will need to find another solution.

**Comment by clinuxrulz** [comment]
I have a hunch that collectCycles() needs to be the very last post(), because Cells update their values via post too, giving the garbage collector false information while cells are in mid rewiring.

**Comment by clinuxrulz** [comment]
Ok forcing collectCycles() to be right at the end of the transaction has fixed the problem I was having. And all tests are passing. I'll make a pull request so it can be reviewed. I think the "dist" folder needs to be checked in too, because node packages do not have a option for a post install script, and I believe node fetches the files direct from the repository. I could be wrong, I'm not experienced enough with node. I can use your help here @dakom, if you have the time.

**Comment by the-real-blackh** [comment]
Thank you @clinuxrulz !

**Comment by clinuxrulz** [comment]
Closing this for now. Re-open if more issues found with this.
