### ISSUE TITLE
Compiled JS missing from npm version 3.0.0

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium-typescript#68]
There may of been a work around for this, so the compiled js does not have to be committed with type script. Just can not remember we finished at.

**Comment by the-real-blackh** [comment]
Thank you very much to anyone who helps with this work!

**Comment by clinuxrulz** [comment]
Just need to remove "dist" folder from ".gitignore" I believe. not sure about the rest of the npm package creation steps, not my area.

**Comment by clinuxrulz** [comment]
Just need to add "dist" back to ".gitignore" and make sure to do a "npm build" *before* a "npm publish". Someone else will need to fix this, I won't have permissions (keys) for "npm publish".

**Comment by clinuxrulz** [comment]
I tried this out today to see if its still not working. But all seems to be fine. the compiled JS was included when i went "npm install sodiumjs --save". I'll close this. Don't forget to do a 3.0.1 version to fix that collectCycles during rewriting cells bug.
