### ISSUE TITLE
include Cell.calm / Cell.partialCalm / Cell.calmRefEq / ... ?

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium-typescript#78]
include Cell.calm / Cell.partialCalm / Cell.calmRefEq / ... ?

Its a fun exercise for the reader, and I know the library is meant to minimalistic. But they get used so often, it can be handy just to have them available.

```Cell.clam``` we already know about.

```Cell.partialCalm``` you send a ```partialEq``` function. (I.E. you know when they are equal, but you do not know when they are not equal).

for ```Cell.clamRefEq``` you do not need to send a eq-function. It can be useful when trying to mimic how some optimisations in React work, but by just using sodium instead of React.

**Comment by the-real-blackh** [comment]
I would be in favour of that.

**Comment by clinuxrulz** [comment]
I'll try that out over the weekend. ```Cell.partialCalm``` implementation turns out to be identical to ```Cell.calm``` so it can be left out.

Another interestingand very useful combinator is:
```
export function cellKeyed<K,A,B>(keyEq: (a:K,b:K)=>boolean, keyExtractor: (a:A)=>K, transform: (a:A)=>B, ca: sodium.Cell<A>): sodium.Cell<B> {
    return cellCalm((a, b) => keyEq(keyExtractor(a), keyExtractor(b)), ca).map(transform);
}
```

Essentially it gives us something as powerful as https://package.elm-lang.org/packages/elm/html/latest/Html-Keyed from elm. (Type B can contain sodium objects that avoid reconstruction, and thus avoid rewriting)

from ```cellKeyed``` you can generate a function:
```export function cellArrayKeyed<K,A,B>(keyEq: (a:K,b:K)=>boolean, keyExtractor: (a:A)=>K, transform: (a:A) => B, cas: sodium.Cell<A[]>): sodium.Cell<B[]>```

which behaves exactly like Html-Keyed from elm.

Such a thing might be too specific for ```sodium-typescript``` though.
