### ISSUE TITLE
Priority queue re-sorts happens too often [Performance]

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/sodium-typescript#82]
On initial wiring all rank start at zero. If a switch occurs followed by a large merge of 1000 streams where each stream fires at the same time, then resorting of the priority queue happens 1000 times during that transaction. Plus the priority queue in use has a naive O(n) update time, leading to O(n^3) for n sodium objects in the merge. (Priority queue emptied and refilled n times)

Estimating the rank from the dependencies initialing before the listen_() could help. And a priority queue based on a array based tree O(log(n)) update could help too.

Note each listen_() creates a sub-transaction and each of these resorts are happening in sub-transactions.

**Comment by clinuxrulz** [comment]
Actually I'm wrong about the priority queue implementation. It does seem to be the O(log(n)) update version. I'll reconsider my own design, having 28000 sodium objects wired up and firing at once seems like a bad idea.

**Comment by clinuxrulz** [comment]
I believe the issue is here: (compiled code)
```
    Vertex.prototype.incRefCount = function (target) {
        var anyChanged = false;
        if (this.refCount() == 0) {
            for (var i = 0; i < this.sources.length; i++)
                this.sources[i].register(this);
        }
        this.targets.push(target);
        target.childrn.push(this);
        if (target.ensureBiggerThan(this.rank))
            anyChanged = true;
        totalRegistrations++;
        return anyChanged;
    };
```

I believe this part:
```
            for (var i = 0; i < this.sources.length; i++)
                this.sources[i].register(this);
```

Should be wrapped in a transaction. To stop the continuous resorting of priority queue when new sodium objects are created in the value of a sodium cell.

**Comment by clinuxrulz** [comment]
I think I know where it is. When processing the ```postQ``` in ```Transaction.close```. All cell values constructing sodium objects cause priority queue resort over and over again. The question is, how best to handle it?

**Comment by the-real-blackh** [comment]
@clinuxrulz Thank you for working on this. I don't have any great idea on this off the top of my head. Maybe there's some way to mark it as dirty and cause a lazy re-evaluation.

**Comment by clinuxrulz** [comment]
I wonder if this is related to the discussion of non-memoized lazy on #79 . If a non-memoized lazy is evaluated multiple times for a LazyCell that creates sodium objects, then those sodium objects will keep being recreated for each cell that uses the value of that cell.

**Comment by clinuxrulz** [comment]
Ignore my 2nd last comment, that is not the cause, will need to keep investigating. The lazy-ness is undone in ```LazyCell``` on ```sampleNoTrans``` and in ```LazySample```.

**Comment by clinuxrulz** [comment]
Closing for now, the problem seems to have gone away. I'd still like to see estimate starting ranks which can be adjusted later (rather than 0). So we can lower the changes of a priority queue resort when new sodium objects are constructed later on in the middle of run-time.
